;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;Catppuccin

[colors]
primary = #1e1e2e
secondary = #3d83b5
text = #FFFFFF
transparent = #FF00000
red =  #ff6669
