;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/menu]
type    = custom/text

content            = 
content-foreground = ${colors.text}
content-padding    = 1

click-left         = rofi -show drun
click-right        = rofi -show window

[module/i3]
type = internal/i3

pin-workspaces=true

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2

label-visible = %index%
label-visible-padding = 2

label-focused = %index%
label-focused-foreground = ${colors.text}
label-focused-background = ${colors.secondary}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-foreground = ${colors.text}
label-unfocused-padding = 2

label-occupied = %index%
label-occupied-foreground = ${colors.text}
label-occupied-padding = 2

label-urgent = %index%
label-urgent-background = ${colors.red}
label-urgent-foreground = ${colors.text}
label-urgent-overline   = ${colors.primary}
label-urgent-underline  = ${colors.primary}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.text}
label-empty-padding = 2


[module/time]
type = internal/date
interval = 1
label-foreground = ${colors.text}
time     =
label    = %time%

[module/date]
type = internal/date
interval = 1
label-foreground = ${colors.text}
time = " %A, %d %B %Y | %l:%M:%S"
label    = %time%

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 1
format-volume            = <ramp-volume><label-volume>
format-volume-foreground = ${colors.text}
label-volume             = %percentage%%
label-volume-padding     = 1

format-muted-foreground     = ${colors.red}
label-muted                 = Muted 
label-muted-padding         = ${self.label-volume-padding}

ramp-volume-0 = 
ramp-volume-1 =
ramp-volume-2 =
ramp-volume-3 = 
ramp-volume-4 = 
ramp-volume-5 = 
ramp-volume-6 = 
ramp-volume-padding = 0

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted-foreground     = ${colors.text}
format-mounted-prefix         = 
format-mounted-prefix-padding = 1
label-mounted                 = %free%
label-mounted-padding         = 0

format-unmounted-prefix       =
label-unmounted               = %mountpoint%: not mounted
label-unmounted-padding       = ${self.label-mounted-padding}

[module/memory]

type = custom/script
exec = "free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2fGB \n", ( $3 / 1024))}'"
format-foreground     = ${colors.text}
interval = 1
click-left = ghostty -e btop

[module/systray]
type = internal/tray
tray-spacing = 10px
